# Generated by Django 5.1.6 on 2025-02-15 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='gm',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'gm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
