# Generated by Django 5.1.6 on 2025-02-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_gm'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='storeid',
            field=models.CharField(default=2608, max_length=8),
            preserve_default=False,
        ),
    ]
