repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Check for the latest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Check for the latest version
    hooks:
      - id: flake8
