# Generated by Django 5.1.6 on 2025-02-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(choices=[('NS', 'No Show'), ('CO', 'Calling Off with Notice'), ('LCO', 'Calling Off Without Notice'), ('L', 'Late ( >10 minutes)'), ('XL', 'Excessively Late (>30 minutes)'), ('P', 'Present')], max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='restaurants.employee')),
            ],
        ),
    ]
